{
  "errors": ["user with this name already exists"]
}
